////////////////////////////////////////////////////////////////////////
/// \class FrameEvent
///
/// \brief   An event generated by a frame container 
///
/// \author  Phil Jones <p.g.jones@qmul.ac.uk>
///
/// REVISION HISTORY:\n
///     29/06/11 : P.Jones - First Revision, new file. \n
///     19/02/12 : P.Jones - Second Revision, rename
///
/// \detail  Events generated by a frame container e.g. close frame.
///
////////////////////////////////////////////////////////////////////////

#ifndef __Viewer_FrameEvent__
#define __Viewer_FrameEvent__

namespace Viewer
{
class FrameEvent
{
public: 
  enum EEventType { eNone, eClosed, eStartMove, eStopMove, eStartResize, eStopResize };

  FrameEvent() : fType( eNone ) { }

  FrameEvent( EEventType type ) : fType( type ) { }

  EEventType fType;
  sf::Vector2<double> fPos; /// < Event position (will be zero if not mouse)
  int fFrameID;
};

} // ::Viewer

#endif
