#!/bin/bash
# Configure script for SNOGoggles, assumes called by snocave makefile
# Author: p.jones22@phyiscs.ox.ac.uk

# Setup and use snocave scons
printf "Using snocave scons\n"
SCONS_BIN=$RAT_SCONS/script:
SCONS_LIB=$RAT_SCONS/engine:

#Now make env.sh file
cat > env.sh << EOF
#!/bin/bash
export VIEWERROOT=`pwd`
export PATH=\$VIEWERROOT/bin:$SCONS_BIN:\$PATH
source $GEANT4_BASE/env.sh
export RATROOT=$RATROOT
export ROOTSYS=$ROOTSYS
export SFMLROOT=$SFMLROOT
export XERCESCROOT=$XERCESCROOT
export GLEWROOT=/usr

export LD_LIBRARY_PATH=\$RATROOT/lib:\$ROOTSYS/lib:\$SFMLROOT/lib:\$XERCESCROOT/lib:\$GLEWROOT/lib:\$G4LIB/\$G4SYSTEM:\$LD_LIBRARY_PATH
# For Mac OS X
export DYLD_LIBRARY_PATH=\$RATROOT/lib:\$ROOTSYS/lib:\$SFMLROOT/lib:\$XERCESCROOT/lib:\$GLEWROOT/lib:\$G4LIB/\$G4SYSTEM:\$DYLD_LIBRARY_PATH
export PYTHONPATH=\$VIEWERROOT/python:$SCONS_LIB\$PYTHONPATH
EOF
[[ -e env.sh ]] && chmod +x env.sh && printf "OK\n"

printf "%-50s" "Generating env.csh..."
cat > env.csh <<EOF
#!/bin/csh
setenv VIEWERROOT `pwd`
setenv PATH "\${VIEWERROOT}/bin:${SCONS_BIN}\$PATH"
setenv RATROOT "${RATROOT}"
setenv ROOTSYS "${ROOTSYS}"
setenv SFMLROOT "${SFMLROOT}"
setenv XERCESCROOT "${XERCESCROOT}"
setenv GLEWROOT "/usr"
if ({\$?LD_LIBRARY_PATH}) then
 setenv LD_LIBRARY_PATH "\${RATROOT}/lib:\${ROOTSYS}/lib:\${SFMLROOT}/lib:\${XERCESCROOT}/lib:\${GLEWROOT}/lib:\${G4LIB}/\${G4SYSTEM}:\$LD_LIBRARY_PATH"
else
 setenv LD_LIBRARY_PATH "\${RATROOT}/lib:\${ROOTSYS}/lib:\${SFMLROOT}/lib:\${XERCESCROOT}/lib:\${GLEWROOT}/lib:\${G4LIB}/\${G4SYSTEM}"
endif
if ({\$?LD_LIBRARY_PATH}) then
 setenv LD_LIBRARY_PATH "\${RATROOT}/lib:\${ROOTSYS}/lib:\${SFMLROOT}/lib:\${XERCESCROOT}/lib:\${GLEWROOT}/lib:\${G4LIB}/\${G4SYSTEM}:\$LD_LIBRARY_PATH"
else
 setenv LD_LIBRARY_PATH "\${RATROOT}/lib:\${ROOTSYS}/lib:\${SFMLROOT}/lib:\${XERCESCROOT}/lib:\${GLEWROOT}/lib:\${G4LIB}/\${G4SYSTEM}"
endif 
if ({\$?PYTHONPATH}) then
 setenv PYTHONPATH "\${VIEWERROOT}/python:$SCONS_LIB:\$PYTHONPATH"
else
 setenv PYTHONPATH "\${VIEWERROOT}/python:$SCONS_LIB"
endif
EOF
[[ -e env.csh ]] && chmod +x env.csh && printf "OK\n"
